# Generated by Django 4.2.3 on 2023-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiscam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scammer',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
