# Generated by Django 4.2.3 on 2023-08-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiscam', '0002_customuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
