# Generated by Django 4.2.3 on 2023-08-17 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiscam', '0003_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='scammer',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scammer',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_scammers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scammer',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
