# Generated by Django 4.2.3 on 2023-08-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiscam', '0003_alter_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
    ]
