# Generated by Django 4.2.3 on 2023-08-17 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antiscam', '0004_scammer_comments_scammer_voters_scammer_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scammer',
            name='comments',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiscam.scammer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
