# Generated by Django 4.2.3 on 2023-08-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiscam', '0005_rename_state_customuser_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
