# Generated by Django 4.2.3 on 2023-08-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiscam', '0006_rename_phone_number_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_number',
            field=models.CharField(default='', max_length=7),
        ),
    ]
