# Generated by Django 4.2.3 on 2023-08-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antiscam', '0006_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='', max_length=13)),
                ('account_name', models.CharField(default='', max_length=255)),
                ('bank_name', models.CharField(default='', max_length=255)),
                ('case_details', models.TextField(default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_reported', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('last_date_reported', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiscam.category')),
                ('scammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiscam.scammer')),
            ],
        ),
    ]
