# Generated by Django 4.2.3 on 2023-08-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiscam', '0009_scammer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scammer',
            name='last_date_reported',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
